spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${MQ_SERVER:10.240.171.99}:${MQ_PORT:9876}

  redis:
    database: 1
    password: redis@App2020
    sentinel:
      master: cam
      nodes: 10.240.63.181:27379,10.240.63.188:27379,192.10.240.63.208:27379

  elasticsearch:
    rest:
      uris:
        - http://${ELASTICSEARCH_SERVER:10.240.171.99}:${ELASTICSEARCH_PORT:9200}
      username: ${ELASTICSEARCH_USERNAME:elastic}
      password: ${ELASTICSEARCH_PASSWORD:elasticsearh@App2020}

archive:
  management:
    medium:
      basePath: ${CQBC_PATH:/cam/cqbc}/upload
      restorePackageUrl: ${CQBC_URL:http://127.0.0.1:8226/SafeStorage}/services/jaxrs/batchOnlineService/getpacketPath
      restorePackagePath: ${CQBC_PATH:/cam/cqbc}/in
  python:
    enabled: true
    ip: ${AI_SERVER:10.240.62.50}
    port: ${AI_PORT:5000}

nginx:
  storage:
    url: http://10.240.62.50:18888
